#!/usr/bin/env bash
set -euo pipefail

# Production deploy: pull -> install -> migrate -> build -> restart services.
# Usage: ./scripts/deploy.sh
# Run as the regular app user. The systemctl restart calls use sudo.
#
# Self-hosted: writes apps/desktop/.env.production.local pinned to PUBLIC_URL
# below, so later desktop packages point at this backend instead of multica.ai.

PUBLIC_URL="https://multica.zxyh.club"

if [ "$(id -u)" = "0" ]; then
  echo "ERROR: don't run this script as root; it would chown build artifacts to root."
  echo "       Run as the regular app user; sudo is invoked only for systemctl restart."
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

setup_toolchain() {
  export PATH="$HOME/.local/bin:$HOME/go/bin:/usr/local/go/bin:$PATH"

  if [ -s "$HOME/.cargo/env" ]; then
    # shellcheck disable=SC1090
    . "$HOME/.cargo/env"
  fi

  if ! command -v pnpm >/dev/null 2>&1; then
    export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
    if [ -s "$NVM_DIR/nvm.sh" ]; then
      # shellcheck disable=SC1091
      . "$NVM_DIR/nvm.sh"
      if [ -f .nvmrc ]; then
        nvm use --silent
      else
        nvm use --silent 22 >/dev/null 2>&1 || nvm use --silent default >/dev/null 2>&1 || true
      fi
    fi
  fi

  if ! command -v pnpm >/dev/null 2>&1 && command -v corepack >/dev/null 2>&1; then
    corepack enable
  fi

  for cmd in git pnpm go make sudo; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      echo "ERROR: missing required command: $cmd" >&2
      echo "PATH=$PATH" >&2
      exit 127
    fi
  done
}

setup_toolchain

FRONTEND_SERVICE="multica-frontend"
BACKEND_SERVICE="multica-backend"

OLD_SHA="$(git rev-parse HEAD)"
echo "==> Repo:       $REPO_ROOT"
echo "==> Current:    $OLD_SHA"

echo ""
echo "==> [1/6] git pull..."
git pull --ff-only

NEW_SHA="$(git rev-parse HEAD)"
if [ "$OLD_SHA" = "$NEW_SHA" ]; then
  echo "    No new commits. Continuing anyway (rebuild may still be desired)."
else
  echo "    Updated: $OLD_SHA -> $NEW_SHA"
  echo "    Changed files:"
  git diff --stat "$OLD_SHA" "$NEW_SHA" | sed 's/^/      /'
fi

echo ""
echo "==> [2/6] pnpm install..."
pnpm install --frozen-lockfile

echo ""
echo "==> [3/6] Database migrations..."
(
  if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    . ./.env
    set +a
  fi
  cd server && go run ./cmd/migrate up
)

host="${PUBLIC_URL#https://}"
echo ""
echo "==> [3a] Pin desktop env -> $PUBLIC_URL"
cat > apps/desktop/.env.production.local <<EOF
# Generated by scripts/deploy.sh; overrides apps/desktop/.env.production.
VITE_API_URL=$PUBLIC_URL
VITE_WS_URL=wss://$host/ws
VITE_APP_URL=$PUBLIC_URL
EOF

echo ""
echo "==> [4/6] Build frontend..."
WEB_BUILD_MAX_OLD_SPACE_SIZE_MB="${MULTICA_WEB_BUILD_MAX_OLD_SPACE_SIZE_MB:-3072}"
WEB_BUILD_MEMORY_MAX="${MULTICA_WEB_BUILD_MEMORY_MAX:-5G}"
WEB_BUILD_SWAP_MAX="${MULTICA_WEB_BUILD_SWAP_MAX:-512M}"
build_node_options="${NODE_OPTIONS:-}"
build_node_options="${build_node_options:+$build_node_options }--max-old-space-size=${WEB_BUILD_MAX_OLD_SPACE_SIZE_MB}"
echo "    Node heap limit: ${WEB_BUILD_MAX_OLD_SPACE_SIZE_MB} MB"
echo "    cgroup MemoryMax: ${WEB_BUILD_MEMORY_MAX}, MemorySwapMax: ${WEB_BUILD_SWAP_MAX}"
sudo systemd-run --wait --pipe --collect \
  -p "MemoryMax=${WEB_BUILD_MEMORY_MAX}" \
  -p "MemorySwapMax=${WEB_BUILD_SWAP_MAX}" \
  --uid="$(id -u)" \
  --gid="$(id -g)" \
  --working-directory="$REPO_ROOT" \
  --setenv="PATH=$PATH" \
  --setenv="NODE_ENV=${NODE_ENV:-production}" \
  --setenv="NODE_OPTIONS=$build_node_options" \
  /usr/bin/env pnpm --filter @multica/web... build

echo ""
echo "==> [5/6] Build backend..."
# Rebase note: do not call `make build` here. The root Makefile includes .env
# as Make syntax, while production .env may contain multiline secrets such as
# private keys; direct go builds keep deployment independent of Make's parser.
VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
(
  cd server
  go build -ldflags "-X main.version=$VERSION -X main.commit=$COMMIT" -o bin/server ./cmd/server
  go build -ldflags "-X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE" -o bin/multica ./cmd/multica
  go build -o bin/migrate ./cmd/migrate
)

echo ""
echo "==> [6/6] Restart services..."
sudo systemctl restart "$BACKEND_SERVICE"
sudo systemctl restart "$FRONTEND_SERVICE"

sleep 2
sudo systemctl --no-pager status "$BACKEND_SERVICE" "$FRONTEND_SERVICE" | sed 's/^/    /'

echo ""
echo "OK: deploy complete. Deployed $NEW_SHA"
echo "Logs: sudo journalctl -u $BACKEND_SERVICE -u $FRONTEND_SERVICE -f"
echo "Desktop: pnpm --filter @multica/desktop package"
